# Generated by Django 4.0.2 on 2022-02-21 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Атрибуты',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название_атрибута', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Значения_атрибутов',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=30)),
                ('Вариант1', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант2', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант3', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант4', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант5', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант6', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант7', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант8', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант9', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант10', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант11', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант12', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант13', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант14', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант15', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант16', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант17', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант18', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант19', models.CharField(blank=True, max_length=30, null=True)),
                ('Вариант20', models.CharField(blank=True, max_length=30, null=True)),
                ('Атрибут', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.атрибуты')),
            ],
        ),
        migrations.CreateModel(
            name='Категории',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Категория1', models.CharField(max_length=30)),
                ('Категория2', models.CharField(blank=True, max_length=30)),
                ('Категория3', models.CharField(blank=True, max_length=30)),
                ('Категория4', models.CharField(blank=True, max_length=30)),
                ('Категория5', models.CharField(blank=True, max_length=30)),
                ('Название', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.значения_атрибутов', verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Поставщики',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Поставщик', models.CharField(max_length=50)),
                ('Вариант1', models.CharField(blank=True, max_length=50)),
                ('Вариант2', models.CharField(blank=True, max_length=50)),
                ('Вариант3', models.CharField(blank=True, max_length=50)),
                ('Вариант4', models.CharField(blank=True, max_length=50)),
                ('Номер_блока', models.CharField(blank=True, max_length=50)),
                ('Атрибут1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Поставщики_Атрибут1', to='adminPanel.атрибуты', verbose_name='Название')),
                ('Атрибут2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Поставщики_Атрибут2', to='adminPanel.атрибуты', verbose_name='Название')),
                ('Атрибут3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Поставщики_Атрибут3', to='adminPanel.атрибуты', verbose_name='Название')),
                ('Атрибут4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Поставщики_Атрибут4', to='adminPanel.атрибуты', verbose_name='Название')),
            ],
            options={
                'unique_together': {('Атрибут1', 'Атрибут2', 'Атрибут3', 'Атрибут4')},
            },
        ),
    ]
