# Generated by Django 4.0.2 on 2022-02-26 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_alter_поставщики_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='категории',
            old_name='Категория2',
            new_name='Категория_Девочкам',
        ),
        migrations.RenameField(
            model_name='категории',
            old_name='Категория3',
            new_name='Категория_Деткам',
        ),
        migrations.RenameField(
            model_name='категории',
            old_name='Категория4',
            new_name='Категория_Женщинам',
        ),
        migrations.RenameField(
            model_name='категории',
            old_name='Категория5',
            new_name='Категория_Мальчикам',
        ),
        migrations.RenameField(
            model_name='категории',
            old_name='Категория1',
            new_name='Категория_Мужчинам',
        ),
        migrations.AddField(
            model_name='категории',
            name='Категория_Унисекс',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='поставщики',
            name='Атрибут1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Поставщики_Атрибут1', to='adminPanel.атрибуты'),
        ),
        migrations.AlterField(
            model_name='поставщики',
            name='Атрибут2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Поставщики_Атрибут2', to='adminPanel.атрибуты'),
        ),
        migrations.AlterField(
            model_name='поставщики',
            name='Атрибут3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Поставщики_Атрибут3', to='adminPanel.атрибуты'),
        ),
        migrations.AlterField(
            model_name='поставщики',
            name='Атрибут4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Поставщики_Атрибут4', to='adminPanel.атрибуты'),
        ),
    ]
