# Generated by Django 4.0.2 on 2022-02-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0004_rename_категория2_категории_категория_девочкам_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='значения_атрибутов',
            name='Единый_размер',
            field=models.BooleanField(default=False),
        ),
    ]
