# Generated by Django 4.0.2 on 2022-02-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0005_значения_атрибутов_единый_размер'),
    ]

    operations = [
        migrations.CreateModel(
            name='Продукты',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Продукт', models.CharField(max_length=500)),
                ('Дата', models.CharField(max_length=30)),
            ],
        ),
    ]
