# Generated by Django 4.0.2 on 2022-02-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0006_продукты'),
    ]

    operations = [
        migrations.AddField(
            model_name='продукты',
            name='Картинка',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
