# Generated by Django 4.0.2 on 2022-02-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0007_продукты_картинка'),
    ]

    operations = [
        migrations.AlterField(
            model_name='продукты',
            name='Картинка',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
